### ISSUE TITLE
Perpetual 'Backend is not connected' Status. Cannot Access LTC Sent to new MustardWallet wallet.

### ISSUE THREAD

**Issue by hodlsolo** [MustardWallet/MustardWalletLTC#12]
### General Description

The client is not able to connect to the backend. I presume that is why my newly created wallet will not update to show receipt of LTC I sent to it from my exchange account.

Please also note that https://mustardwallet.com/ currently results in a "502 Bad Gateway" error:

### How To Reproduce?

1. Run Mustard Wallet on Windows 10
2. See this message in the footer:  "Backend is not connected."

### Screenshots

https://preview.redd.it/z16c27no5ky61.png?width=1426&format=png&auto=webp&s=7c22c7a2fd298ff25400c056fa69f448e57dbe92
(originally provided by another user)

### Operating System

Windows 10

### Logs

Here's what's written when I launch the app...

> 2021-06-29 15:45:01 INFO	Program (43)	Mustard Wallet for Litecoin GUI started (41c63d33-8699-4068-98a4-fc01ce35cf92).
2021-06-29 15:45:02 INFO	TransactionStore (29)	MempoolStore.InitializeAsync finished in 33 milliseconds.
2021-06-29 15:45:02 INFO	TransactionStore (29)	ConfirmedStore.InitializeAsync finished in 1 milliseconds.
2021-06-29 15:45:02 INFO	AllTransactionStore (28)	InitializeAsync finished in 42 milliseconds.
2021-06-29 15:45:02 INFO	TorProcessManager (251)	Starting Tor monitor...
2021-06-29 15:45:02 INFO	Global (168)	TorProcessManager is initialized.
2021-06-29 15:45:02 INFO	TorProcessManager (75)	Tor is already running.
2021-06-29 15:45:03 INFO	Global (392)	Loaded AddressManager from `C:\Users\david\AppData\Roaming\MustardWalletLTC\Client\AddressManager\AddressManagerltc-main.dat`.
2021-06-29 15:45:04 INFO	IndexStore (45)	InitializeAsync finished in 2 seconds.
2021-06-29 15:45:04 INFO	BitcoinStore (39)	InitializeAsync finished in 2 seconds.
2021-06-29 15:45:08 INFO	BitcoindRpcProcessBridge (58)	Litecoin Core is not yet ready... Reason: No connection could be made because the target machine actively refused it.
2021-06-29 15:45:12 INFO	BitcoindRpcProcessBridge (58)	Litecoin Core is not yet ready... Reason: Loading wallet...
2021-06-29 15:45:14 INFO	BitcoindRpcProcessBridge (52)	RPC connection is successfully established.
2021-06-29 15:45:14 INFO	CoreNode (171)	Started Litecoin Core.
2021-06-29 15:45:14 INFO	CoreNode (49)	CreateAsync finished in 10 seconds.
2021-06-29 15:45:14 INFO	HostedServices (51)	Started Software Update Checker.
2021-06-29 15:45:14 INFO	HostedServices (51)	Started Block Notifier.
2021-06-29 15:45:14 INFO	HostedServices (51)	Started RPC Monitor.
2021-06-29 15:45:14 INFO	HostedServices (51)	Started RPC Fee Provider.
2021-06-29 15:45:14 INFO	Global (290)	Start connecting to nodes...
2021-06-29 15:45:14 INFO	Global (314)	Start synchronizing filters...
**2021-06-29 15:45:16 ERROR	PeriodicRunner (73)	NBitcoin.RPC.NoEstimationException: The FeeRate couldn't be estimated because of insufficient data from Bitcoin Core. Try to use smaller nBlock, or wait Bitcoin Core to gather more data.
   at NBitcoin.RPC.RPCClient.EstimateSmartFeeAsync(Int32 confirmationTarget, EstimateSmartFeeMode estimateMode)
   at WalletWasabi.BitcoinCore.RpcClientBase.EstimateSmartFeeAsync(Int32 confirmationTarget, EstimateSmartFeeMode estimateMode)
   at NBitcoin.RPC.RPCClientExtensions.EstimateSmartFeeAsync(IRPCClient rpc, Int32 confirmationTarget, EstimateSmartFeeMode estimateMode, Boolean simulateIfRegTest, Boolean tryOtherFeeRates)
   at NBitcoin.RPC.RPCClientExtensions.EstimateHalfFeesAsync(IRPCClient rpc, IDictionary`2 estimations, Int32 smallTarget, Int32 smallFee, Int32 largeTarget, Int32 largeFee, EstimateSmartFeeMode estimateMode, Boolean simulateIfRegTest, Boolean tolerateBitcoinCoreBrainfuck)
   at NBitcoin.RPC.RPCClientExtensions.EstimateAllFeeAsync(IRPCClient rpc, EstimateSmartFeeMode estimateMode, Boolean simulateIfRegTest, Boolean tolerateBitcoinCoreBrainfuck)
   at WalletWasabi.BitcoinCore.Monitoring.RpcFeeProvider.ActionAsync(CancellationToken cancel)
   at WalletWasabi.Bases.PeriodicRunner.ExecuteAsync(CancellationToken stoppingToken)**

...Then, the **last entry above** repeats itself again and again.

### Wasabi Version

Which wasabi release are you using? 0.1.7.0

Where did you download it from?  https://github.com/MustardWallet/MustardWalletLTC/releases/tag/v0.1.7.0

**Comment by gabrielkrieger** [comment]
Thanks for reporting . The Backend had been killed by the out of memory killer . I've upgraded the server to a hosting package with 50% more RAM , which should prevent this issue from popping up every so often . 

Should be good now . Can you give it a go please ? Sorry for the wait ..

**Comment by hodlsolo** [comment]
Thank you very much for spending the time and resources ($$$) on upgrading your server (and for the reply).  I'm pleased to report that all seems to be working like it should from my end:
- Tor is running
- Full node is synchronized
- Backend is connected
- Price is showing the latest price

After some effort, I was able to restore the wallet I originally created in Mustard into Electrum.  But I'm glad to know everything will work nicely once I move it back again.

Have a good one!

**Comment by gabrielkrieger** [comment]
Yeah, and the increased RAM seems to really help, the OOM issues seem to be resolved. Thanks!

**Comment by gabrielkrieger** [comment]
Awesome ! :)

**Comment by lettawi** [comment]
Same problem happening right now.

**Comment by gabrielkrieger** [comment]
Indeed - the backend went out of memory again , it just took a lot longer for the issue to occur since now that we have more RAM in the machine . I've restarted the backend . A permanent fix would be to re-sync with the upstream Wasabi backend , assuming the leak has been fixed there ...
