### ISSUE TITLE
Coinjoin not working

### ISSUE THREAD

**Issue by Kenny1217** [MustardWallet/MustardWalletLTC#5]
### General Description
The coinjoin function doesn't work. The coinjoin goes to the signing phase and the bar goes red. Then after that it resets and goes back to the registration phase. No coinjoin transaction is never made. 

### How To Reproduce?
1. Add funds to queue.
2. Funds get get registered.
3. It makes it to the signing phase.
4. Coinjoin just goes back to registration

### Operating System
Windows 10 64-bit

### Logs
2020-07-19 15:19:21 INFO	Global (605)	Transaction Notification (Information): Receive Confirmed - 0.022 LTC - a6b172b3ba1c4e8d1e05e74cd5316e0b28cf66ca0cd6b2631dbda8f50c156a7f
2020-07-19 15:19:21 INFO	MempoolService (119)	Start cleaning out mempool...
2020-07-19 15:19:22 INFO	MempoolService (129)	182 transactions were cleaned from mempool.
2020-07-19 15:19:39 INFO	AliceClient (100)	Round (563), Alice (907c94ae-7289-4d18-8882-589d8f16d3da): Registered 1 inputs.
2020-07-19 15:19:39 INFO	ClientState (60)	Coin removed from the waiting list: 1:a6b172b3ba1c4e8d1e05e74cd5316e0b28cf66ca0cd6b2631dbda8f50c156a7f.
2020-07-19 15:19:57 INFO	AliceClient (156)	Round (563), Alice (907c94ae-7289-4d18-8882-589d8f16d3da): Confirmed connection. Phase: ConnectionConfirmation.
2020-07-19 15:20:17 INFO	WasabiSynchronizer (257)	Downloaded filter for block 1879814.
2020-07-19 15:20:24 INFO	CoinJoinClient (444)	Round (563) Bob Posted outputs: 1.
2020-07-19 15:20:24 INFO	MempoolService (119)	Start cleaning out mempool...
2020-07-19 15:20:25 INFO	MempoolService (129)	19 transactions were cleaned from mempool.
2020-07-19 15:20:28 INFO	AliceClient (234)	Round (563), Alice (907c94ae-7289-4d18-8882-589d8f16d3da): Acquired unsigned CoinJoin: 26f5b3f2c3782b6b4bf3e0d9ad6a4622878beb62422b3054961c74e4c651c981.
2020-07-19 15:20:28 INFO	AliceClient (250)	Round (563), Alice (907c94ae-7289-4d18-8882-589d8f16d3da): Posted 1 signatures.
2020-07-19 15:20:44 INFO	ClientState (429)	Coin added to the waiting list: 1:a6b172b3ba1c4e8d1e05e74cd5316e0b28cf66ca0cd6b2631dbda8f50c156a7f, but its registration is not allowed till 60 seconds, because this coin might already be spent.
2020-07-19 15:20:44 INFO	ClientState (452)	Round (563) removed. Reason: It's not running anymore.
2020-07-19 15:20:44 INFO	ClientState (470)	Round (565) added.

### Wasabi Version
Mustard Wallet version 0.1.7.0

**Comment by gabrielkrieger** [comment]
Thank you very much for reporting this so clearly.

I found this error in the log files:

`2020-07-19 15:20:41 INFO        CoordinatorRound (70)   New round (565) is created.
        BaseDenomination: 0.02 LTC.
        AdjustedConfirmationTarget: 576.
        CoordinatorFeePercent: 0.015%.
        AnonymitySet: 3.
2020-07-19 15:20:41 INFO        CoordinatorRound (1104) Round (563): Aborted. Reason: Could not broadcast the CoinJoin: 26f5b3f2c3782b6b4bf3e0d9ad6a4622878beb62422b3054961c74e4c651c981..
2020-07-19 15:20:41 ERROR       CoordinatorRound (1105) NBitcoin.RPC.RPCException: dust (code 64)
   at NBitcoin.RPC.RPCResponse.ThrowIfError()
   at NBitcoin.RPC.RPCClient.SendCommandAsyncCore(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendCommandAsync(RPCRequest request, Boolean throwIfRPCError)
   at NBitcoin.RPC.RPCClient.SendRawTransactionAsync(Byte[] bytes)
   at WalletWasabi.BitcoinCore.RpcClientBase.SendRawTransactionAsync(Transaction transaction)
   at WalletWasabi.CoinJoin.Coordinator.Rounds.CoordinatorRound.BroadcastCoinJoinIfFullySignedAsync()
`

I have seen this "dust" issue before when small amounts are involved .

A workaround is probably to increase the minimal mixing amounts but I am going to look deeper into this first ASAP !

**Comment by gabrielkrieger** [comment]
The issue was triggered by the ( sometimes tiny ) coordinator fee being added and causing a " dust " error from NBitcoin or Bitcoin Core .

I re-enabled the Rule that drops the coordinator fee if it's less than 0.0003 LTC , now 0.0001 LTC . I also changed the minimal mixing amount from 0.01 LTC to 0.1 LTC and slightly increased the coordinator fee from 0.015% to 0.02% . Finally , I added some Debugging to troubleshoot this more easily .

That seems to have fixed the dust error . Can you confirm that we can close this issue ?

Thank you again for reporting the Issue and sorry for the inconvenience !

**Comment by Kenny1217** [comment]
Yup that seems to fix it. Thanks!

**Comment by gabrielkrieger** [comment]
Minimal coordinator fee is now 0.00003 LTC because that seems to be the lowest we can go without triggering the dust error . Thanks for testing , this means a lot for the project at such an early Stage !
